id: P004549
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN4273
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་ཁྲིད་ཡིག་ཡེ་ཤེས་བླ་མ།
  author: ''
  volumes:
    8102815ab84b43e2a00ff891b13aa037:
      image_group_id: I3CN4292
      title: ''
      volume_number: 1
      total_pages: 172
