id: I3613DC16
legacy_id: P004549
ocr_import_info:
  bdrc_scan_id: W3CN4273
  source: bdrc
  ocr_info:
    timestamp: '2020-03-29T18:15:11'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T11:34:15.133411+00:00'
last_modified: 2022-08-27 19:34:27.622271
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W3CN4273
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW3CN4273
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྫོགས་པ་ཆེན་པོ་ཀློང་ཆེན་སྙིང་ཐིག་གི་ཁྲིད་ཡིག་ཡེ་ཤེས་བླ་མ།
  author: ཀུན་མཁྱེན་འཇིགས་མེད་གླིང་པ།
statistics:
  ocr_word_mean_confidence_index: 0.9507261308044214
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I3CN4292:
    source_metadata:
      id: http://purl.bdrc.io/resource/I3CN4292
      total_pages: 172
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I3CN4292.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9507261308044214
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
